;; Generated by :claw at 2026-06-12T08:47:05.071164Z
(asdf:defsystem #:claw-torch-bindings
  :description "Bindings generated by claw-torch"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi)
  :components
  ((:file "bindings/x86_64-unknown-linux-gnu" :if-feature (:and :x86-64 :linux))))
#-(:or (:and :x86-64 :linux))
(warn "Current platform unrecognized or unsupported by claw-torch-bindings system")